// Generated by CoffeeScript 1.11.1
var exec, fs, lib, path;

path = require('path');

fs = require('fs');

lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');

exec = require(lib + '/post');
