// Generated by CoffeeScript 1.11.1
var READ, args, chatter, colors, exec, fs, lib, message, myIP, nick, path, port, request, send;

myIP = require('my-ip');

colors = require('colors');

args = process.argv.slice(2);

console.log('============================================='.cyan);

console.log('Your ' + 'IPv6'.yellow + ' is ' + (myIP('IPv6')).green);

console.log('Your ' + 'IPv4'.yellow + ' is ' + (myIP('IPv4')).green);

console.log('Port'.yellow + ': ' + ((args[3] || 2467) + '').magenta);

console.log('============================================='.cyan);

READ = function(q, f) {
  var readline, ret, rl;
  ret = null;
  readline = require('readline');
  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
  return rl.question(q, function(answer) {
    rl.close();
    return f(answer);
  });
};

exec = require('child_process').exec;

request = require('request');

path = require('path');

fs = require('fs');

lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');

send = function(nick, chatter, message) {
  var port;
  port = 2467;
  request.post({
    url: 'http://' + chatter + ':' + port,
    form: {
      message: message,
      nick: nick.blue
    }
  });
  request.post({
    url: 'http://127.0.0.1:' + port,
    form: {
      message: message,
      nick: 'You'.blue
    }
  });
  return READ('>>> '.blue, function(message) {
    return send(nick, chatter, message);
  });
};

if (!args[0]) {
  READ('Your ' + 'nickname'.yellow + ': ', function(nick) {
    return READ('Your ' + 'chatter\'s IP'.yellow + ': ', function(chatter) {
      exec('start node ' + lib + '/server ' + chatter);
      console.log('Enter ' + 'message'.yellow + ':');
      return READ('>>> '.blue, function(message) {
        return send(nick, chatter, message);
      });
    });
  });
} else {
  chatter = args[0];
  message = args[2];
  nick = args[1];
  port = args[3] || 2467;
  request.post({
    url: 'http://' + chatter + ':' + port,
    form: {
      message: message,
      nick: nick.blue
    }
  });
  request.post({
    url: 'http://127.0.0.1:' + port,
    form: {
      message: message,
      nick: 'You'.blue
    }
  });
}
