// Generated by CoffeeScript 1.11.1
var args, chatter, colors, http, port, queryString, request, s;

args = process.argv.slice(2);

chatter = args[0];

http = require('http');

request = require('request');

queryString = require('query-string');

port = args[1] || 2467;

colors = require('colors');

s = http.createServer();

s.on('request', function(request, response) {
  var data;
  data = '';
  request.on('data', function(chunk) {
    data += chunk.toString();
  });
  request.on('end', function() {
    var parsed;
    parsed = queryString.parse(data);
    console.log(parsed.nick + ': ' + parsed.message);
    response.write('This is console chat :D');
    response.end();
  });
});

s.listen(port);

console.log('Chatting with ' + 'http://'.green + chatter.green + ':'.green + (port + '').magenta);

console.log('Messages:');
