// Generated by CoffeeScript 1.11.1

/*
████──███──████───█─█──███──████──███──███
█──█──█────█──█───█─█───█───█──█──█────█
████──███──█─██───█─█───█───████──███──███
█─█───█────█──█───█─█───█───█─█───█──────█
█─█───███──█████──███──███──█─█───███──███
───────────────██
 */

/*
╔═╗ ║║ ║ ╔╗
║╔╗ ║║ ║ ║║
╚═╝ ╚╝ ╚ ╠╝
 */
var clean, fs, gulp, gulpIF, rename, runSequence, spawn, uglify;

gulp = require('gulp');

uglify = require('gulp-uglify');

gulpIF = require('gulp-if');

fs = require('fs');

clean = require('gulp-clean');

rename = require('gulp-rename');

runSequence = require('run-sequence');

spawn = require('child_process').exec;


/*
███──████──███──█──█──███
─█───█──█──█────█─█───█
─█───████──███──██────███
─█───█──█────█──█─█─────█
─█───█──█──███──█──█──███
 */

gulp.task('lib', function() {
  return gulp.src('lib/*.js').pipe(uglify()).pipe(gulp.dest('../lib/'));
});

gulp.task('bin', function() {
  return gulp.src('bin/*.js').pipe(uglify()).pipe(gulp.dest('../bin/'));
});

gulp.task('build', ['lib', 'bin']);
